# Generated by Django 5.0b1 on 2023-10-31 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Casino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('bonus_first_deposit', models.CharField(blank=True, max_length=200, null=True)),
                ('bonus_second_deposit', models.CharField(blank=True, max_length=200, null=True)),
                ('bonus_third_deposit', models.CharField(blank=True, max_length=200, null=True)),
                ('bonus_code', models.CharField(blank=True, max_length=50, null=True)),
                ('affiliate_link', models.CharField(blank=True, max_length=200, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
