# Generated by Django 5.0b1 on 2023-10-31 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casinos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='casino',
            name='rank',
            field=models.TextField(blank=True, max_length=4, null=True),
        ),
    ]
