# Generated by Django 5.0b1 on 2023-10-31 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casinos', '0002_casino_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casino',
            name='rank',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
