# Generated by Django 5.0b1 on 2023-11-02 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casinos', '0006_casino_deposit_methods_casino_providers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/provider'),
        ),
    ]
