# Generated by Django 5.0b1 on 2023-11-02 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casinos', '0007_alter_provider_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='casino',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='images/casino_icon'),
        ),
        migrations.AlterField(
            model_name='depositmethod',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='images/deposit_method'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='images/provider'),
        ),
    ]
