# Generated by Django 5.0b1 on 2023-11-02 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casinos', '0008_casino_icon_alter_depositmethod_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casino',
            name='highlight',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
