# Generated by Django 5.0b1 on 2023-11-05 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casinos', '0009_casino_highlight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casino',
            name='bonus_code',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='bonus_first_deposit',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='bonus_second_deposit',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='bonus_third_deposit',
        ),
        migrations.AddField(
            model_name='casino',
            name='bonus',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='casino',
            name='bonus_max',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='casino',
            name='bonus_type',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='casino',
            name='bonus_wager',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
