# Generated by Django 5.0b1 on 2023-11-05 15:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casinos', '0010_remove_casino_bonus_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casino',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='images/casino_icon', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'gif', 'svg'])]),
        ),
    ]
