# Generated by Django 5.0b1 on 2023-11-05 15:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casinos', '0012_alter_depositmethod_icon_alter_provider_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositmethod',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='images/deposit_method', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'gif', 'svg'])]),
        ),
    ]
