# Generated by Django 5.0b1 on 2023-11-05 15:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casinos', '0013_alter_depositmethod_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casino',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='images/casino_icon', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'gif', 'svg'])]),
        ),
        migrations.AlterField(
            model_name='provider',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='images/provider', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'gif', 'svg'])]),
        ),
    ]
