# Generated by Django 5.0b1 on 2023-11-06 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casinos', '0014_alter_casino_icon_alter_provider_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='casino',
            name='bonus_first_deposit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='casino',
            name='bonus_second_deposit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='casino',
            name='bonus_third_deposit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='depositmethod',
            name='rank',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='rank',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
