# Generated by Django 5.0b1 on 2023-11-06 14:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casinos', '0016_alter_casino_options_alter_depositmethod_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casino',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='images/casino_icon', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'gif', 'svg', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='depositmethod',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='images/deposit_method', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'gif', 'svg', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='provider',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='images/provider', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'gif', 'svg', 'webp'])]),
        ),
    ]
