# Generated by Django 5.0b1 on 2023-11-13 06:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casinos', '0017_alter_casino_icon_alter_depositmethod_icon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('rank', models.PositiveIntegerField(blank=True, max_length=3, null=True)),
                ('icon', models.FileField(blank=True, null=True, upload_to='images/provider', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'gif', 'svg', 'webp'])])),
            ],
        ),
        migrations.RemoveField(
            model_name='casino',
            name='bonus_type',
        ),
        migrations.AddField(
            model_name='casino',
            name='bonus_type',
            field=models.ManyToManyField(to='casinos.bonustype'),
        ),
    ]
