# Generated by Django 5.0b1 on 2023-11-13 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casinos', '0019_remove_bonustype_icon_remove_bonustype_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casino',
            name='bonus_type',
        ),
        migrations.AddField(
            model_name='casino',
            name='bonus_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='casinos.bonustype'),
        ),
    ]
