# Generated by Django 5.0b1 on 2023-11-13 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casinos', '0020_remove_casino_bonus_type_casino_bonus_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='casino',
            name='bonus_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
