# Generated by Django 5.0b1 on 2023-11-23 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casinos', '0022_casino_free_spins'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name='casino',
            name='affiliate_link',
            field=models.CharField(default='https://slotalarm.com', max_length=200),
        ),
        migrations.AlterField(
            model_name='casino',
            name='bonus',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='casino',
            name='bonus_max',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='casino',
            name='bonus_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='casinos.bonustype'),
        ),
        migrations.AlterField(
            model_name='casino',
            name='bonus_wager',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='casino',
            name='rank',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='depositmethod',
            name='rank',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='rank',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='casino',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='casinos.country'),
        ),
    ]
