# Generated by Django 5.0b1 on 2023-11-23 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casinos', '0023_country_alter_casino_affiliate_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casino',
            name='country',
        ),
        migrations.AddField(
            model_name='casino',
            name='country',
            field=models.ManyToManyField(to='casinos.country'),
        ),
    ]
