# Generated by Django 4.2.6 on 2024-04-15 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casinos', '0025_socialmedia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casino',
            name='highlight',
        ),
    ]
