# Generated by Django 4.2.6 on 2024-04-15 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casinos', '0026_remove_casino_highlight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casino',
            name='bonus_first_deposit',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='bonus_second_deposit',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='bonus_third_deposit',
        ),
    ]
