# Generated by Django 4.2.6 on 2024-04-15 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('casinos', '0027_remove_casino_bonus_first_deposit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casino',
            name='bonus_type',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='casinos.bonustype'),
        ),
    ]
