# Generated by Django 4.2.6 on 2024-04-15 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('casinos', '0029_alter_casino_bonus_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casino',
            name='bonus_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='casinos.bonustype'),
        ),
    ]
