# Generated by Django 4.2.6 on 2024-04-29 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casinos', '0031_alter_casino_bonus_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SocialMedia',
        ),
    ]
