# Generated by Django 5.0.4 on 2024-10-25 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casinos', '0031_alter_casino_bonus_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CasinoPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcome_text', models.TextField(blank=True, help_text='Text for the welcome section', verbose_name='Welcome Text')),
                ('info_text', models.TextField(blank=True, help_text='SEO-optimized text for the bottom of the page', verbose_name='SEO Info Text')),
            ],
        ),
    ]
