# Generated by Django 5.0.4 on 2024-10-27 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casinos', '0032_casinopagecontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='CasinoSpotlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_text', models.TextField(blank=True, help_text='Text for the spotlight casino', verbose_name='Promotional Text')),
                ('casino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spotlight', to='casinos.casino')),
            ],
        ),
    ]
