# Generated by Django 5.0.4 on 2024-10-27 10:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casinos', '0033_casinospotlight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casinopagecontent',
            name='info_text',
            field=ckeditor.fields.RichTextField(blank=True, help_text='SEO-optimized text for the bottom of the page', verbose_name='SEO Info Text'),
        ),
        migrations.AlterField(
            model_name='casinopagecontent',
            name='welcome_text',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Text for the welcome section', verbose_name='Welcome Text'),
        ),
        migrations.AlterField(
            model_name='casinospotlight',
            name='promo_text',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Text for the spotlight casino', verbose_name='Promotional Text'),
        ),
    ]
