# Generated by Django 4.2.6 on 2024-04-29 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('casinos', '0032_delete_socialmedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('twitch', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('dlive', models.URLField(blank=True, null=True)),
                ('kick', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('css_file', models.CharField(max_length=100)),
                ('casinos', models.ManyToManyField(to='casinos.casino')),
                ('social_media', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='subpages.socialmedia')),
            ],
        ),
    ]
