# Generated by Django 4.2.6 on 2024-04-30 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subpages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subpage',
            name='social_media',
        ),
        migrations.AddField(
            model_name='subpage',
            name='dlive',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subpage',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subpage',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subpage',
            name='kick',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subpage',
            name='twitch',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subpage',
            name='youtube',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='SocialMedia',
        ),
    ]
