# Generated by Django 4.2.6 on 2024-04-30 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('casinos', '0032_delete_socialmedia'),
        ('subpages', '0002_remove_subpage_social_media_subpage_dlive_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubpageCasino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affiliate_link', models.URLField(blank=True, null=True)),
                ('casino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casinos.casino')),
                ('subpage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subpages.subpage')),
            ],
        ),
        migrations.AlterField(
            model_name='subpage',
            name='casinos',
            field=models.ManyToManyField(through='subpages.SubpageCasino', to='casinos.casino'),
        ),
    ]
